### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by BurnMe2** [Creepsky/creepMiner#438]
Before submitting your issue, please review the following checklist:

### Subject of the issue
Segmentation fault appears and the creepMiner is crashing. Sometime it comes after some hours and sometimes it runs for abou 1-2 Weeks and then suddenly out of nowhere the Miner crashes.

### Your environment
CreepMiner 18.3
Mintlinux 18.3
Firefox 61.0.1

### Steps to reproduce
Just running CreepMiner. There is no real step to reduce the issue.

### Expected behavior
No segmentation fault

### Actual behavior
Segmantion fault during scanning.

### Other information
Somebody else had this issue too. I think perhaps i could recompile the creepMiner and then trying again. I will tell the results here.

**Comment by BurnMe2** [comment]
Hi,

i recompiled the CreepMiner. For the last 11 days the CreepMiner runs fine then it crashes with Segmentation fault. There are only PoC2 fiels on the HDD and nothing else. So don't know what to do now.  It runs fine for several days but not stable for me so i have to check every day.

Has somene advice how to minimize Segmentation fault error ? What tells me Segmentation fault ?

**Comment by BurnMe2** [comment]
So im am testing on. I am forwarding 2 CreepMiner PC to the 1 CreepMiner Server (where the burstcoin server is running).

My results  are on every PC the during Plot scanning the CreepMiner 1.8.3 suddenly ends and crahes with segentation fault. I think once a week the Miner crahes. With 3 PC its 3 of 7 days. So the system has to be monitored all the time.  So in the long run its a lot of monitoring work with downtime because during night the crash happens during the sleep time.

Actually i was able to get some more information on my log file.  In my opinion the miner finds a nonce and the suddenly is thinking the nonce (that was found) was for another block (than the expected actual one).  In Detail CreepMiner thinks the found nonce was for the block before. But why is CreepMiner this thinking ? When i restard the CreepMiner everything runs fine. The Burstcoin Server (actually 2.2.3) is running without problems. 

Even when CreepMiner is thinking that the nonce was for the last block it shouldn't stop scanning the plot files.

HERE is my lOG of the Segmentation fault error:

10.10.2018 07:35:19 (18492, /home/travis/build/Creepsky/creepMiner/src/network/NonceSubmitter.cpp, 124, Debug): JSON confirmation (1d 16:50:46)	
10.10.2018 07:35:19 (18492, /home/travis/build/Creepsky/creepMiner/src/network/NonceSubmitter.cpp, 209, Debug): Found nonce was for the last block, stopped submitting! (1d 16:50:46)

**Comment by Integrative** [comment]
Same here, Ubuntu 18.04 - Kernel 4.15.0-38 (stock), AMD GPU 18.40 (rx570/4GB)

dmesg:
509.751435] creepMiner[3074]: segfault at ffffffe8 ip 00007fc02fca7f2e sp 00007fbfe67fb9e0 error 4

**Comment by BurnMe2** [comment]
Hi Integrative,

i am still on testing. Actually i am using BRS 2.2.4 Wallet. I am hoping that this new Wallet solves the Segmentation fault problem. Perhaps CreepMiner is adressing the right way but the Wallet 2.2.3 gives a wrong time stamp or something like that. 

So my advice check the new BRS 2.2.4 Burstcoin Wallet.

I am testing or one week now and there was no  more segmentation fault error unti now.

Can you thell which version of BRS Wallet you are using ? And wich database Maria or H2 ?

In my case i am using Maria database.  When this error appears again I even in BRS 2.2.4 i would try H2 databse perhabs there could be an issue too.

I tell my results of testing the BRS 2.2.4 in some weeks when its stable in this forum

**Comment by Leozolt** [comment]
I have segmentation fault (core dumped) program exit issues as well. It fails after 0,5 to 10 days runtime.
Ubuntu 16.04 miner 1.8.3 & 1.8.2 using poc1 plots, using mixed poc1 & 2 files and using only poc2 files.
8 files on 8 drives in usb enclosures. had an issue befoe that i could fix using multiple instances  #346.

**Comment by Creepsky** [comment]
Could someone please build it with debug symbols: -DCMAKE_BUILD_TYPE=RELWITHDEBINFO or -DCMAKE_BUILD_TYPE=DEBUG.

DEBUG is slow, but shows exactly what went wrong when it crashed, while RELWITHDEBINFO is fast, but because of compiler optimisations the core will not be as readable as with DEBUG.

After the crash, you can view the core file with gdb like this: `gdb /path/to/creepMiner /path/to/core`. You'll need gdb for this, of course (`sudo apt-get install gdb` on Debian).

When gdb has booted up, type in `bt`, then copy paste it here please.

**Comment by skarasov** [comment]
Arch linux x64 - 
Core was generated by `./creepMiner-d'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fde30196290 in Poco::Net::HTTPSession::setKeepAlive(bool) ()
   from /home/h/.conan/data/Poco/1.9.0/pocoproject/stable/package/7a9b32b6c4a0456b3443454c9a7266139657db92/lib/libPocoNet.so.60
[Current thread is 1 (Thread 0x7fde2d65c840 (LWP 8458))]
(gdb) bt
#0  0x00007fde30196290 in Poco::Net::HTTPSession::setKeepAlive(bool) ()
   from /home/h/.conan/data/Poco/1.9.0/pocoproject/stable/package/7a9b32b6c4a0456b3443454c9a7266139657db92/lib/libPocoNet.so.60
#1  0x000056314957ffdc in Burst::Miner::run (this=0x7ffc574910a0)
    at /home/h/creepminer/src/mining/Miner.cpp:150
#2  0x0000563149574e7c in main (argc=1, argv=0x7ffc574918b8)
    at /home/h/creepminer/src/main.cpp:252

**Comment by skarasov** [comment]
All above because miner ip was blocked in local wallet.
Maybe, error message and exit if miner can't connect to or wrong answer from wallet?
